---
version: '3.8'
services:
 voting:
  image: dockersamples/examplevotingapp_vote
  ports:
   - 5050:80
 myredis:
  image: redis
  ports:
   - 6060:6379
 worker:
  image: dockersamples/examplevotingapp_worker
 mypostgres:
  image: postgres
  ports: 
   - 7070:5432
 result:
  image: dockersamples/examplevotingapp_result
  ports:
   - 8080:80  
...     
  
